spring:
  profiles:
    active: @spring.active@
    #active: local
  #配置静态资源路径
  mvc:
    static-path-pattern: /pages/**
mybatis-plus:
  mapper-locations: classpath:cn.suvue.discipline.modular.mapper.xml/*Mapper.xml
  #别名包(实体扫描),多个包用逗号或分号隔开
  type-aliases-package: cn.suvue.discipline.modular.entity
  global-config:
    #数据库相关配置
    db-config:
      #驼峰下划线转换
      table-underline: true
  #原生配置
  configuration:
    map-underscore-to-camel-case: true